version: 1.0.0.{build}

image: 
- Visual Studio 2017
- ubuntu

environment:
  APPVEYOR_RDP_PASSWORD: Atest123!
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  matrix:
  # MinGW
  - name: win32
    platform: mingw
    QTDIR: C:\Qt\5.12.2\mingw73_64
    QTTOOLS: C:\Qt\Tools\mingw730_64\bin
    suffix: mingw

init:
  - set PATH=%PATH%;%QTDIR%\bin;%QTTOOLS%
  - set CC=%QTTOOLS%\gcc.exe
  - set CXX=%QTTOOLS%\g++.exe
  - set Qt5_DIR=%QTDIR%\lib\cmake\Qt5
  - set PATH=%PATH:C:\Program Files\Git\usr\bin=%

before_build:
  - cd C:\projects\qpointergrabber
  - md build

build_script:
  - cd build
  - cmake .. -G"CodeBlocks - MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release 
  - mingw32-make
