version: 1.0.0.{build}

image: 
- Visual Studio 2017

environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  matrix:
  # MinGW
  - name: win32
    platform: mingw
    qt: 5.12.2\mingw73_64
    suffix: mingw

init:
  - set PATH=C:\Program Files\Git\cmd;C:\Qt\%qt%\bin;C:\Qt\%qt%\lib;C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin\;C:\msys64\mingw64\bin
  - set makefiles="MSYS Makefiles"

before_build:
  - cd C:\projects\qpointergrabber
  - md build

build_script:
  - cd build
  - cmake .. -G %makefiles% -DCMAKE_BUILD_TYPE=Release 
