version: 1.0.0.{build}

image: 
- Visual Studio 2017
- Ubuntu1804

environment:
  APPVEYOR_SSH_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDxSEgVy4B2b2chvVIO0bA/gpW98qFueGxGYNoZvTBvRCx1oFB+TZ5wX3eQFH6G/xlTjXz0cvkvC2R+P9ScQHy3FucE52H8bbrtf8kxy8AEP54DHSf15/WruwR0uvsbQzpUQFKBl32KrnWpgjjRuuafkqOc08uDrZyfdYOTzrssPxTFQFRoG7SktoVduTHICPAy5KJIM2W7sOe2x6lqKPojgulhZNj09l5psn/+WQyoPPrEQJFfLTumqo5TCB6mMnR6KnRLy3xpsvV9MEZnP7C8klUPojbF258IW8708Wqt4i41vSKIQY2P0nIqCZ96Ngi8JsxO7wn4lMF+U1reQRZd
  APPVEYOR_RDP_PASSWORD: Atest123!
  APPVEYOR_YML_DISABLE_PS_LINUX: true

init:
  - cmd: set QTDIR=C:\Qt\5.12.4\mingw73_64
  - cmd: set QTTOOLS=C:\Qt\Tools\mingw730_64\bin
  - cmd: set PATH=%PATH%;%QTDIR%\bin;%QTTOOLS%
  - cmd: set CC=%QTTOOLS%\gcc.exe
  - cmd: set CXX=%QTTOOLS%\g++.exe
  - cmd: set Qt5_DIR=%QTDIR%\lib\cmake\Qt5
  - cmd: set PATH=%PATH:C:\Program Files\Git\usr\bin=%

before_build:
  - cmd: cd C:\projects\qpointergrabber
  - cmd: md build
  - sh:  sudo apt install -y qtbase5-dev libqt5x11extras5-dev
  - sh:  sudo apt install -y openbox menu
  - sh:  Xvfb :1 -screen 0 1920x1080x24+32 -fbdir /var/tmp &
  - sh:  sleep 10
  - sh:  export DISPLAY=:1
  - sh:  openbox &
  - sh:  sleep 3

build_script:
  - cmd: cd build
  - cmd: cmake -G"CodeBlocks - MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release ..
  - cmd: mingw32-make -j 4
  - sh: mkdir build
  - sh: cd build
  - sh: cmake -DCMAKE_BUILD_TYPE=Release ..
  - sh: make -j 4

# In case we need debug build
# on_finish:
# - sh: export APPVEYOR_SSH_BLOCK=true
# - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -